[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["rmstorm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
daggy = "0.7.0"
